<div class="home-page__trending-now">
    <?php
        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('trending')->toHtml();
    ?>
</div>

<script>
    require([
        'jquery',
        'slick'
    ], function ($) {
        $(document).ready(function () {
            $('.product-items').slick({
            slidesToShow: 4,
            rows: 1,
            dots :false,
            arrows: false,
            responsive: [
                    {
                    breakpoint: 1024,
                    settings: {
                        slidesToShow: 3,
                         slidesToScroll: 3,
                         infinite: true,
                         arrows: false,
                         dots :false,
                    }
                    },
                    {
                    breakpoint: 768,
                    settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1,
                        speed: 300,
                        infinite: true,
                        arrows: true,
                        dots :false,
                    }
                    },
                    {
                        breakpoint: 600,
                        settings: {
                            slidesToShow:1,
                            slidesToScroll: 1,
                            infinite: true,
                            arrows: false,
                            dots :false,
                        }
                    },
                    {
                    breakpoint: 480,
                    settings: {
                        slidesToShow: 1,
                        slidesToScroll: 1,
                        infinite: true,
                        arrows: false,
                        dots :false,
                     }
                    }
                ]
            });
        });
    });
</script>